title: Iftikhar Zahid
logo: /assets/img/logo.png
description: Apps dev (React Native) & Ai Enthusiast | Learning and Exploring Fortunes of Tech.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
